### ISSUE TITLE
Roadmap to 0.4.10

### ISSUE THREAD

**Issue by nponeccop** [bnoguchi/everyauth#488]
I'm going to port an in-house project from 0.4.5 and node 0.10 to 0.4.9 and node 8.x (LTS boron) as the latter seems least broken for the dependencies my project has.

So I volunteer to take over maintenance of `everyauth` from @bnoguchi 

My tasks are essentially:
- [ ] bump and/or fix the deps
- [ ] fix incompatibilities
- [ ] integrate fixes from other branches/PRs
- [ ] do as many small/easy fixes as humanly possible

As for fixing individual providers, I'm only interested in getting the big ones working, with my arbitrary definition of "big":
- google
- facebook
- twitter
- linkedin
- vkontakte

Of course I'll accept fixes for extra ones, but I won't test them myself.

**Comment by nponeccop** [comment]
My branch is https://github.com/bnoguchi/everyauth/compare/master...nponeccop:hotfix-0.4.10

So far:

- the package is installed without deprecation or security audit warnings with node 8.x
- Google example in `example/server.js` works (as long as you change the credentials in `example/conf.js`, of course)
- twitter example works too

Fixing Facebook would require an HTTPS server, because Facebook doesn't support non-https redirection URLs anymore. So I'm postponing fixing the Facebook for now, because my own app can't migrate easily to HTTPS, so I'm not motivated enough to fix Facebook as I can't use it myself.

Vkontakte I can't test due to a combination of personal and political reasons, so only LinkedIn remains to be checked.
